#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &
#bspc rule -a Screenkey manage=off
#$HOME/.screenlayout/screen.sh &

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Start System Applications ##
~/.config/bspwm/autostart.sh &

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

## Configurations --------------------------------------------#

#### BSPWM coloring ####
bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

## Automatic Monitor Profile Setup ##
#~/.config/bspwm/profile.sh &
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
#bspc monitor -d 一 二 三 四 五 六 七 八 九 十 
#bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor ${monitor} -n "$name" -d 1 2 3 4 5 6 7 8
#bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII' 'IX'
#bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '' '' ''
		let name++
	done
}
workspaces

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_LVDS-1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)

#### BSPWM configuration ####

bspc config border_width	1
bspc config window_gap		4
bspc config border_radius	6
bspc config split_ratio		0.50
bspc config top_padding		0
bspc config bottom_padding	0
bspc config left_padding	0
bspc config right_padding	0

bspc config click_to_focus				false
bspc config borderless_monocle			true
bspc config gapless_monocle				true
bspc config focus_by_distance			true
bspc config focus_follows_pointer		true
bspc config history_aware_focus			true
bspc config remove_disabled_monitors	true
bspc config merge_overlapping_monitors	true
bspc config paddingless_monocle			true
bspc config single_monocle				false

# Enable Super Keys For Menu
# ksuperkey -e 'Super_L=Alt_L|F1' &
# ksuperkey -e 'Super_R=Alt_L|F1' &

#Super (Mod1=<Alt>, Mod4=<Super>)
bspc config pointer_modifier mod4

## Auto-hide cursor ##
unclutter --timeout 10 --jitter 2 --exclude-root --ignore-scrolling -b &

#   Set mouse 1 to move floating windows
bspc config pointer_action1 move

#   Mouse 2 button resizes the window by side
bspc config pointer_action2 resize_side

## Set mouse cursor outside windows ##
xsetroot -cursor_name left_ptr &

## Window rules ----------------------------------------------#

# remove all rules first
# bbspc rule -r *:*

# FLoting ## Rules ##
bspc rule -a "*:Toolkit:Picture-in-Picture" \
     state=floating sticky=on follow=off focus=on \
     rectangle=640x360

# 1 > terminal
bspc rule -a UXTerm state=floating centered=true sticky=on
bspc rule -a XTermB state=floating border=off
bspc rule -a Alacritty desktop='^1' follow=on focus=on
bspc rule -a Terminal desktop='^1' state=floating border=off
bspc rule -a Terminator desktop='^1' border=off
bspc rule -a Tilix desktop='^1' state=floating border=off
bspc rule -a xfce4-terminal state=floating sticky=on border=off
declare -a term=(UXTerm Alacrity)
for i in ${term[@]}; do
   bspc rule -a $i desktop='^1' state=floating follow=on focus=on; done

# 2 > web
bspc rule -a Firefox-esr desktop='^2' follow=on focus=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Nyxt desktop='^2'
bspc rule -a Brave desktop='^2'
bspc rule -a PaleMoon desktop='^2'
bspc rule -a Vivaldi desktop='^2'
bspc rule -a Microsoft edge desktop='^2'
bspc rule -a firefox desktop='^2' state=floating
bspc rule -a firefoxdeveloperedition desktop='^2' follow=off
bspc rule -a Links2 desktop='^2'
bspc rule -a qutebrowser desktop='^2' follow=on
declare -a web=(Links2)
for i in ${web[@]}; do
   bspc rule -a $i desktop='^2' state=floating follow=on focus=on; done

# 3 > files
bspc rule -a Thunar desktop='^3' follow=on focus=on
bspc rule -a Thunar:Dialog state=floating center=true
bspc rule -a Pcmanfm desktop='^3' border=off
bspc rule -a ranger desktop='^3' state=floating
bspc rule -a Org.gnome.Nautilus desktop='^3' follow=on focus=on
declare -a files=(ranger)
for i in ${files[@]}; do
   bspc rule -a $i desktop='^3' state=floating follow=on focus=on; done

# 4 > office and docs
bspc rule -a QComicBook desktop='^4'
bspc rule -a Xreader desktop='^4' state=tiled follow=on
bspc rule -a Zeal desktop='^4'
bspc rule -a '*:libreoffice' desktop='^4' state=tiled
bspc rule -a '*:soffice' desktop='^4'
bspc rule -a Mousepad state=floating center=on
bspc rule -a Simple-scan desktop='^4' state=floating center=on border=off
declare -a office=()
for i in ${office[@]}; do
   bspc rule -a $i desktop='^4' state=floating follow=on focus=on; done

# 5 > code
bspc rule -a Code desktop='^5'
bspc rule -a vim desktop='^5'
bspc rule -a nvim desktop='^5'
bspc rule -a PyCharm desktop='^5'
bspc rule -a Geany desktop='^5' follow=on focus=on
bspc rule -a VSCodium desktop='^5' follow=on focus=on
declare -a code=()
for i in ${code[@]}; do
   bspc rule -a $i desktop='^5' state=floating follow=on focus=on; done

# 6 > Communication
bspc rule -a discord desktop='^6' follow=on
bspc rule -a Skype desktop='^6' state=floating
bspc rule -a Slack desktop='^6' state=floating
bspc rule -a thunderbird desktop='^6' follow=on focus=on
bspc rule -a TelegramDesktop desktop='^6' follow=on focus=on
bspc rule -a whatsdesk desktop='^6' follow=on focus=on
bspc rule -a Hexchat desktop='^6' follow=on focus=on
bspc rule -a Filezilla desktop='^6' state=floating
bspc rule -a JDownloader desktop='^6' state=floating
bspc rule -a qBittorrent desktop='^6' state=floating
bspc rule -a deluge desktop='^6'
declare -a comm=(JDonwnloader)
for i in ${comm[@]}; do
   bspc rule -a $i desktop='^6' state=floating follow=on focus=on; done

# 7 > media
bspc rule -a kdenlive desktop='^7'
bspc rule -a MysqlWorkbenchCommunity desktop='^7'
bspc rule -a Audacious desktop='^7' state=floating follow=on focus=on
bspc rule -a Zathura desktop='^7' state=tiled follow=on
bspc rule -a Inkscape desktop='^7' follow=on focus=on
bspc rule -a Gimp-2.10 desktop='^7' follow=on focus=on
bspc rule -a deemix-gui desktop='^7' follow=on focus=on
bspc rule -a SMPlayer desktop='^7' state=floating follow=on state=floating
bspc rule -a SMTube desktop='^7' state=floating follow=on state=floating
bspc rule -a vlc desktop='^7' state=floating
declare -a media=(Audacity obs Hypnotix.py)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^7' state=floating follow=on focus=on; done
   
# 8 > games
bspc rule -a valheim desktop='^8' follow=on focus=on
bspc rule -a snowrunner desktop='^8' follow=on focus=on
bspc rule -a Steam desktop='^8' state=floating follow=off
bspc rule -a wine desktop='^8' state=floating
declare -a games=(discord Steam)
for i in ${games[@]}; do
   bspc rule -a $i desktop='^8' state=floating follow=on focus=on; done

# 9 > settings
bspc rule -a (?i)virtualbox state=floating
bspc rule -a GParted desktop='^1' follow=on focus=on
bspc rule -a 'Software' desktop='^1' follow=on focus=on
declare -a settings=(Lxappearance Arandr \
Xfce4-power-manager-settings Exo-helper-1 \
Nm-connection-editor Virt-manager)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^1' state=floating follow=on focus=on; done

# special rules
bspc rule --add mpv state=floating sticky=on
bspc rule -a protontricks state=floating centered=true sticky=on
bspc rule -a xarchiver state=floating border=off
bspc rule -a Archive Manager state=floating
bspc rule -a File-roller state=floating
bspc rule -a Pamac-manager state=floating  center=on border=off
bspc rule -a Gpick state=floating center=on rectangle=960x540+0+0
bspc rule -a Gdebi state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Catfish state=floating center=on rectangle=960x540+0+0
bspc rule -a Mictray state=floating centered=true
bspc rule -a Pulseaudio-equalizer-gtk state=floating focus=off
bspc rule -a alsamixer state=floating center=on border=off
bspc rule -a Minitube state=floating
bspc rule -a calamares state=floating center=on border=off
bspc rule -a Parcellite state=floating
bspc rule -a File Transfer* state=floating
bspc rule -a fpakman state=floating
bspc rule -a Galculator state=floating
bspc rule -a Emoji Picker state=floating
bspc rule -a Standard Notes state=floating
bspc rule -a GParted state=floating center=on border=off
bspc rule -a Lightdm-settings state=floating center=on border=off
bspc rule -a Lxrandr state=floating
bspc rule -a Yad state=floating focus=on floating=on
bspc rule -a Nvidia-settings state=floating focus=on floating=on
bspc rule -a Xfce4-appfinder state=floating focus=on floating=on 
bspc rule -a MuseScore Play Panel state=floating
bspc rule -a Nitrogen state=floating center=on border=off
bspc rule -a Oblogout state=floating center=on border=off
bspc rule -a octopi state=floating center=on border=off
bspc rule -a About Pale Moon state=floating center=on border=off
bspc rule -a qt5ctn state=floating center=on border=off
bspc rule -a Qtconfig-qt4 state=floating center=on border=off
bspc rule -a Timeshift-gtk state=floating
bspc rule -a Xfburn state=floating
bspc rule -a Blueman-manager state=floating centered=true
bspc rule -a Blueman-services state=floating centered=true
bspc rule -a Display state=floating centered=true
bspc rule -a Protonvpn state=floating centered=true
bspc rule -a popup-calendar.sh state=floating
bspc rule -a __main__.py state=floating focus=on center=on
bspc rule -a Gnome-system-monitor state=tiled focus=on center=on
bspc rule -a (?i)virtualbox state=floating
bspc rule -a (?i)System-config-printer.py state=floating
bscp rule -a polybar manage=off
bspc rule -a '*:Kunst' sticky=on layer=below border=off focus=off
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

# Lauch notification daemon
dunst \
-geom "280x50-10+42" -frame_width "1" -font "Iosevka Custom 9" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &
